jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # docker stuff add by doing travis encrypt DOCKER_USER=<> --add and travis encrypt DOCKER_PASS=<> --add
  - secure: ASbS99/EusI/vAQp0rW/MIG+mdilqgP5MF6Se55GINxDBDL6auBwo5E5UmSI/WY3MA8oBa1eZ2MMOr4fQbFhpTp5fo52BefKFrn/mXSyxbtiF7fmdIczOPMdHnyYZ8g22u5dNVGP7RQqdzttxWXicfIfWJt/gPgIaJf+cIYuc0QlNxKYeYv8p3p2/tCzWySVXcSaJwdi36IBA/K7DzurpLIR+CgZG9S1ZuYnve4+Bt0YWm5YNt6yHKdPbWATvLVraNbmH7CLPB+COaEciLV4S1M48ArqN+52YcZMH3C3NAecnxvANvI5WWZ1UtcaSL6l9Y4/8Rp+eA95YeMn3PdmVCFt27TIWwsgKkDzXE1zYUIgcVvQZomgXPCxGIqaFo7ZnY+LjDumNI9XcP4ZWp/cP0Si/rMRdPP/zKjc7QmbmZvTKhvyZKUtdWq047aPitRID2k6GS3nkhNh4G44YMULyshZ/ECazwfilnJ09UM4329SGp6UHGdMxhxzKMi0iMDM0VUBKag7RlZYiMQx1o4NsQZSTa7eajF+fbBCqtZbXjJIVgP1mJUi0BbvCudCsCyOcJd586fM2E2VIemJVHNSSgx4QxZVHncaquIwd1e9KPTVF4lSIIhFn/0rZXVWpIMBpxnukcaPI5pNC9nHy1U2aPr1anIOFkgjCt6VeoOb2vg=
  - secure: fZJNmizHd6LAnB6rAnG2Ngqm/ZDZh/Jy6WQtfx8N0FNCV1NgG3JAgLuGg2CgpNAZfRL9BTJBTWAa+ltepxmx7/Clb4hKoxB1LAHbaZlBLb1U9IgffEwlS17tscF1fjK2nMw3k8ftxQ3fl09O/V+LAl0b9/Rmy2f1Z0S+jg0gA7C2rmieJt92wKOZZ45ZFsplgjChqg42ZsnN2ODeoDCY87cIhAa63i1y8kiAb5/F36hbNg5y3mVxI1IqJ5xxHY+Poa784XJ+oOv0a9P8me+ufTLNHWu1OOijrYos4AjuWUiYgSrNKHvg2qYrCuotpjpf9XK2DCjtzxoIhBVhs5PLH5SZhavnQKhmrQ11ViSWGF6QZzIK9wMFpr8hekeYI7yHhcam1Ux1Ke1V2ICaoMC188jWLJU8bhf3AwCt6i4VJAxsH9SW75cA9T4PoNJmkTC9zqyX4h+FQKYGhxoX17+BTBQ1g03nB9y/xvE4ZGZfI7CPSPZJee3oudQw7gDrlHg3a1wGgmmZTvGg0toeWKSDk8x/3mJ+s/qOj4a2YliwuA2frMhoSgmq9EyaLi6ssL2D7NndLB4huzvDSVfoXVjzUU4OlXcj9yz8Er1vDX0hoa/+p5kvU/yFqzxwCqMRbF0EbismFkO4Ljhaw+rDzd7C7PmHmY/OLhFixHE9FCFMsuk=
deploy:
  provider: releases
  api_key: 
  file: target/triber-todo-command-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-command
    branch: develop
    tags: true
  api-key:
    secure: xnPiYuNSwpXwcUHBKm7lSiIKrG+OuCcLeVCxoBSfkoTF1zmctKnorPgT1ncJXwWVAPmEGItW91/FzCEHIMK4RfqgbE9rGAJt2FK+bcCEphA/52A0q4sCaHln0mNR5eztCSCKGij/IsRWQarl8XZIYGec1fnypQBiRyDZTYdJxA6dRYEnL1+CNPv5aAZ1Z96xZZeiaRXwSRvVWWWlJeFFuZxhGkNBkcmCDCLlS0HwFSRwsYGs5MaXshUPfY5P70vqXwlg7z0TkdKq6Q59XabetMYGvZD8T2dJxGQBAssMvR/dB232guYt3Zu65bI98WVldnhKdNiaNHQ1hJHgrgQKghl4VVQ4w0LJuE9iyX/rqB/eXoFYHYbSJObdOntTcYZzSia3AmGAGibLugzK1ANf8cwvLDQipO+pX/flMvbZ5hBjeVU76J1Fu1xtWytUqgrpQCCRIizGXR7yAPwdfjDXxkLMOJ9XW2aiGiIKMLDynoVEIFbXGXX3tUYF2vPL0KVsl8i6GbeUh8Accp4M3ChBJCHnyAM29VxSl9oJUjNnm7zjl+1gBU/DY4im3wXN6V4Z8xJAodYANGi+CBbL7yse8eGebyrdhIaypl4OS7BEX/gme0TvUz1A1JQn/jzlQytpM8u1nj3ZtsP1MbxUDw6gwJdKjhxK6NbLaA1lKvG39wA=
