spring:
  profiles: dev
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      repositories:
        enabled: false

info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"